import { itinerary } from '../itinerary.js'; 
// (import like this) => import { itinerary } from '../assets/sampleItineraryData';

export const itinerary = [
    {
      date: "2023-06-23",
      lng: -75.1652,
      lat: 39.9546,
      name: "Philadelphia",
      desc: "Visit the Liberty Bell and Independence Hall, where the Declaration of Independence and the U.S. Constitution were signed.",
      city: "Philadelphia, PA",
      time: 0,
      temp: 80,
    },
    {
      date: "2023-06-25",
      lng: -79.9311,
      lat: 37.2719,
      name: "Natural Bridge",
      desc: "Marvel at the stunning Natural Bridge, a limestone arch spanning 215 feet in height and 90 feet in width.",
      city: "Natural Bridge, VA",
      time: 4,
      temp: 82,
    },
    {
      date: "2023-06-26",
      lng: -81.6557,
      lat: 35.7822,
      name: "Asheville",
      desc: "Enjoy the scenic beauty of the Blue Ridge Mountains and visit the Biltmore Estate, a grand mansion and gardens.",
      city: "Asheville, NC",
      time: 4.5,
      temp: 79,
    },
    {
      date: "2023-06-27",
      lng: -83.0458,
      lat: 42.3314,
      name: "Detroit",
      desc: "Discover the rich history of Detroit's automotive industry at the Henry Ford Museum and explore the vibrant downtown area.",
      city: "Detroit, MI",
      time: 7,
      temp: 77,
    },
    {
      date: "2023-06-28",
      lng: -86.1581,
      lat: 39.7684,
      name: "Indianapolis",
      desc: "Visit the Indianapolis Motor Speedway, home of the famous Indy 500 race, and explore the downtown's cultural attractions.",
      city: "Indianapolis, IN",
      time: 5,
      temp: 84,
    },
    {
      date: "2023-06-29",
      lng: -87.6298,
      lat: 41.8781,
      name: "Chicago",
      desc: "Experience the vibrant cityscape of Chicago, including Millennium Park, Navy Pier, and the Art Institute of Chicago.",
      city: "Chicago, IL",
      time: 3.5,
      temp: 82,
    },
    {
      date: "2023-06-30",
      lng: -90.0715,
      lat: 29.9511,
      name: "New Orleans",
      desc: "Immerse yourself in the unique culture of New Orleans. Explore the French Quarter, indulge in delicious cuisine, and enjoy live jazz music.",
      city: "New Orleans, LA",
      time: 9,
      temp: 89,
    },
    {
      date: "2023-07-01",
      lng: -94.5786,
      lat: 39.0997,
      name: "Kansas City",
      desc: "Discover the vibrant arts scene of Kansas City, visit the Nelson-Atkins Museum of Art, and savor Kansas City-style barbecue.",
      city: "Kansas City, MO",
      time: 11,
      temp: 85,
    },
    {
      date: "2023-07-02",
      lng: -104.9903,
      lat: 39.7392,
      name: "Denver",
      desc: "Explore the Rocky Mountains and enjoy outdoor activities. Visit the Denver Art Museum and stroll along the 16th Street Mall.",
      city: "Denver, CO",
      time: 8,
      temp: 78,
    },
    {
      date: "2023-07-03",
      lng: -106.6297,
      lat: 35.0844,
      name: "Santa Fe",
      desc: "Experience the rich culture and history of Santa Fe. Explore the art galleries, visit the historic Plaza, and savor Southwest cuisine.",
      city: "Santa Fe, NM",
      time: 6.5,
      temp: 83,
    },
    {
      date: "2023-07-04",
      lng: -108.5007,
      lat: 45.5231,
      name: "Billings",
      desc: "Celebrate Independence Day in Billings and enjoy the fireworks display. Take in the scenic beauty of Montana's landscapes.",
      city: "Billings, MT",
      time: 8.5,
      temp: 75,
    },
    {
      date: "2023-07-05",
      lng: -111.891,
      lat: 40.7608,
      name: "Salt Lake City",
      desc: "Discover the natural beauty of Utah. Visit Temple Square and explore the outdoor recreation opportunities in the nearby mountains.",
      city: "Salt Lake City, UT",
      time: 6.5,
      temp: 82,
    },
    {
      date: "2023-07-06",
      lng: -114.0719,
      lat: 51.0447,
      name: "Calgary",
      desc: "Experience the vibrant city of Calgary. Visit the Calgary Stampede, explore the city's parks, and enjoy panoramic views from the Calgary Tower.",
      city: "Calgary, AB",
      time: 9.5,
      temp: 73,
    },
    {
      date: "2023-07-07",
      lng: -122.3321,
      lat: 47.6062,
      name: "Seattle",
      desc: "Explore the iconic landmarks of Seattle, including the Space Needle, Pike Place Market, and enjoy stunning views of the Puget Sound.",
      city: "Seattle, WA",
      time: 12,
      temp: 75,
    },
    {
      date: "2023-07-08",
      lng: -123.1207,
      lat: 49.2827,
      name: "Victoria",
      desc: "Take a ferry to Victoria, British Columbia. Explore the picturesque Butchart Gardens and enjoy the charm of downtown Victoria.",
      city: "Victoria, BC",
      time: 3.5,
      temp: 73,
    },
    {
      date: "2023-07-09",
      lng: -118.2437,
      lat: 34.0522,
      name: "Los Angeles",
      desc: "Arrive in Los Angeles and explore the diverse neighborhoods, visit the Hollywood Walk of Fame, and enjoy the beautiful beaches.",
      city: "Los Angeles, CA",
      time: 18,
      temp: 88,
    }
  ];
  
  
  
  
  
  